# Generated by Django 5.0.2 on 2024-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursishnoma', '0002_alter_response_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='ip_address',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
