# Generated by Django 5.0.2 on 2024-03-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursishnoma', '0003_alter_response_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_main',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
