# Generated by Django 5.0.2 on 2024-03-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursishnoma', '0005_mainquestion_alter_question_question_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pursishnoma.mainquestion'),
        ),
    ]
