# Generated by Django 5.0.2 on 2024-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursishnoma', '0006_response_question_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='only_text',
            field=models.BooleanField(default=False, verbose_name='Только текст'),
        ),
    ]
